CREATE TABLE IF NOT EXISTS [Makes] (
	[ID]		INTEGER,
	[Name]		TEXT		 NOT NULL,
	PRIMARY KEY ([ID] AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS [Models] (
	[ID]		INTEGER,
	[MakeID]	INTEGER 	NOT NULL,
	[Name]		TEXT 		NOT NULL,
	
	PRIMARY KEY ([ID] AUTOINCREMENT),
	CONSTRAINT  [FK_MakeID] FOREIGN KEY ([MakeID]) REFERENCES [Makes]([ID])
);