/* Store in memory */
PRAGMA temp_store = 2;

DROP TABLE IF EXISTS [tmpNewMakes];

CREATE TEMP TABLE [tmpNewMakes] (
       [ID]   INT PRIMARY KEY,
	   [Name] TEXT);
	   
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (1, 'Acura');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (2, 'Alfa Romeo');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (3, 'AM General');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (4, 'American Motors Corporation');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (5, 'ASC Incorporated');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (6, 'Aston Martin');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (7, 'Audi');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (8, 'Aurora Cars Ltd');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (9, 'Autokraft Limited');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (10, 'Avanti Motor Corporation');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (11, 'Azure Dynamics');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (12, 'Bentley');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (13, 'Bertone');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (14, 'Bill Dovell Motor Car Company');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (15, 'Bitter Gmbh and Co. Kg');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (16, 'BMW');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (17, 'BMW Alpina');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (18, 'Bugatti');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (19, 'Buick');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (20, 'BYD');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (21, 'Cadillac');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (22, 'CCC Engineering');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (23, 'Chevrolet');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (24, 'Chrysler');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (25, 'CODA Automotive');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (26, 'Consulier Industries Inc');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (27, 'CX Automotive');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (28, 'Dabryan Coach Builders Inc');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (29, 'Dacia');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (30, 'Daewoo');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (31, 'Daihatsu');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (32, 'Dodge');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (33, 'E. P. Dutton, Inc.');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (34, 'Eagle');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (35, 'Environmental Rsch and Devp Corp');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (36, 'Evans Automobiles');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (37, 'Excalibur Autos');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (38, 'Federal Coach');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (39, 'Ferrari');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (40, 'Fiat');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (41, 'Fisker');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (42, 'Ford');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (43, 'General Motors');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (44, 'Genesis');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (45, 'Geo');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (46, 'GMC');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (47, 'Goldacre');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (48, 'Grumman Allied Industries');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (49, 'Grumman Olson');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (50, 'Honda');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (51, 'Hummer');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (52, 'Hyundai');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (53, 'Import Foreign Auto Sales Inc');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (54, 'Import Trade Services');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (55, 'INEOS Automotive');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (56, 'Infiniti');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (57, 'Isis Imports Ltd');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (58, 'Isuzu');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (59, 'J.K. Motors');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (60, 'Jaguar');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (61, 'JBA Motorcars, Inc.');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (62, 'Jeep');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (63, 'Kandi');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (64, 'Karma');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (65, 'Kenyon Corporation Of America');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (66, 'Kia');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (67, 'Koenigsegg');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (68, 'Laforza Automobile Inc');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (69, 'Lambda Control Systems');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (70, 'Lamborghini');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (71, 'Land Rover');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (72, 'Lexus');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (73, 'Lincoln');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (74, 'London Coach Co Inc');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (75, 'London Taxi');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (76, 'Lordstown');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (77, 'Lotus');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (78, 'LucID');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (79, 'Mahindra');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (80, 'Maserati');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (81, 'Maybach');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (82, 'Mazda');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (83, 'Mcevoy Motors');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (84, 'McLaren Automotive');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (85, 'Mercedes-Benz');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (86, 'Mercury');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (87, 'Merkur');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (88, 'MINI');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (89, 'Mitsubishi');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (90, 'Mobility Ventures LLC');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (91, 'Morgan');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (92, 'Nissan');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (93, 'Oldsmobile');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (94, 'Pagani');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (95, 'Panos');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (96, 'Panoz Auto-Development');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (97, 'Panther Car Company Limited');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (98, 'PAS Inc - GMC');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (99, 'PAS, Inc');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (100, 'Peugeot');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (101, 'Pininfarina');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (102, 'Plymouth');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (103, 'Polestar');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (104, 'Pontiac');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (105, 'Porsche');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (106, 'Quantum Technologies');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (107, 'Qvale');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (108, 'Ram');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (109, 'Red Shift Ltd.');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (110, 'Renault');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (111, 'Rivian');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (112, 'Rolls-Royce');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (113, 'Roush Performance');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (114, 'RUF Automobile');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (115, 'Ruf Automobile Gmbh');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (116, 'S and S Coach Company  E.p. Dutton');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (117, 'Saab');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (118, 'Saleen');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (119, 'Saleen Performance');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (120, 'Saturn');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (121, 'Scion');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (122, 'Shelby');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (123, 'smart');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (124, 'Spyker');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (125, 'SRT');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (126, 'Sterling');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (127, 'STI');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (128, 'Subaru');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (129, 'Superior Coaches Div E.p. Dutton');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (130, 'Suzuki');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (131, 'Tecstar, LP');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (132, 'Tesla');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (133, 'Texas Coach Company');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (134, 'Toyota');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (135, 'TVR Engineering Ltd');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (136, 'Vector');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (137, 'Vinfast');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (138, 'Vixen Motor Company');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (139, 'Volga Associated Automobile');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (140, 'Volkswagen');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (141, 'Volvo');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (142, 'VPG');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (143, 'Wallace Environmental');
INSERT INTO [tmpNewMakes] ([ID], [Name]) VALUES (144, 'Yugo');

INSERT INTO [Makes] ([Name])
SELECT [NEW].[Name]
  FROM [tmpNewMakes] AS [NEW]
       LEFT OUTER JOIN [Makes] AS [MAK]
	                ON [NEW].[Name] = [MAK].[Name]
 WHERE [MAK].[ID] IS NULL;
 
DROP TABLE [tmpNewMakes];